### ISSUE TITLE
run_once Configure containerd

### ISSUE THREAD

**Issue by pocake-svn** [jmutai/k8s-pre-bootstrap#8]
If uncomment the line below 
- name: Configure containerd
  ansible.builtin.shell: containerd config default > /etc/containerd/config.toml
#run_once: true

the hosts can not join to cluster with error message: 
`[preflight] Some fatal errors occurred:
	[ERROR CRI]: container runtime is not running: output: time="2021-12-18T19:30:25+03:00" level=fatal msg="getting status of runtime: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"`

To resolve the issue I commented line run_once

**Comment by jmutai** [comment]
Sorted
